; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs =
  wari_3G
  wari_3G_v2
  wari_4G
  wari_lidar
  wari_lidar_cellular
  wari_lidar_lora
  wari_v1
  wari_v20
  wari_v21

[env:base]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino
lib_deps =
  makuna/RTC
  greiman/SdFat
  paulstoffregen/AltSoftSerial
  rocketscream/Low-Power
  garmin/LIDAR-Lite
  marzogh/SPIMemory
check_tool = clangtidy
check_flags = clangtidy: --config-file=.clang-tidy
extra_scripts = pre:find_ino_files.py
check_skip_packages = yes

[env:wari_3G]
extends = env:base
custom_sensor_dir = wari_3G
check_src_filters =
  +<wari_3G/*>
  -<wari_3G/src/XBee_dev*>
build_src_filter =
  -<*>
  +<wari_3G/*>

[env:wari_3G_v2]
extends = env:base
custom_sensor_dir = wari_3G_v2
check_src_filters =
  +<wari_3G_v2/*>
  -<wari_3G_v2/src/XBee_dev*>
build_src_filter =
  -<*>
  +<wari_3G_v2/*>

[env:wari_4G]
extends = env:base
custom_sensor_dir = wari_4G
check_src_filters =
  +<wari_4G/*>
  -<wari_4G/src/XBee_dev*>
build_src_filter =
  -<*>
  +<wari_4G/*>

[env:wari_lidar]
extends = env:base
custom_sensor_dir = wari_lidar
check_src_filters =
  +<wari_lidar/*>
  -<wari_lidar/src/XBee_dev*>
build_src_filter =
  -<*>
  +<wari_lidar/*>

[env:wari_lidar_cellular]
extends = env:base
custom_sensor_dir = wari_lidar_cellular
check_src_filters =
  +<wari_lidar_cellular/*>
  -<wari_lidar_cellular/src/XBee_dev*>
build_src_filter =
  -<*>
  +<wari_lidar_cellular/*>

[env:wari_lidar_lora]
extends = env:base
custom_sensor_dir = wari_lidar_lora
lib_deps =
  makuna/RTC
  greiman/SdFat
  paulstoffregen/AltSoftSerial
  rocketscream/Low-Power
  garmin/LIDAR-Lite
  marzogh/SPIMemory
  mikem/RadioHead
check_src_filters =
  +<wari_lidar_lora/*>
build_src_filter =
  -<*>
  +<wari_lidar_lora/*>

[env:wari_v1]
extends = env:base
custom_sensor_dir = wari_v1
lib_deps =
  makuna/RTC
  greiman/SdFat
  rocketscream/Low-Power
check_src_filters =
  +<wari_v1/*>
build_src_filter =
  -<*>
  +<wari_v1/*>

[env:wari_v20]
extends = env:base
custom_sensor_dir = wari_v2.0
lib_deps =
  makuna/RTC
  greiman/SdFat
  rocketscream/Low-Power
check_src_filters =
  +<wari_v2.0/*>
build_src_filter =
  -<*>
  +<wari_v2.0/*>

[env:wari_v21]
extends = env:base
custom_sensor_dir = wari_v2.1
lib_deps =
  makuna/RTC
  greiman/SdFat
  paulstoffregen/AltSoftSerial
  garmin/LIDAR-Lite
  marzogh/SPIMemory
  rocketscream/Low-Power
check_src_filters =
  +<wari_v2.1/*>
build_src_filter =
  -<*>
  +<wari_v2.1/*>
